extends:
- "@redhat-cloud-services/eslint-config-redhat-cloud-services"
- "plugin:cypress/recommended"
rules:
  rulesdir/forbid-pf-relative-imports: off
  no-only-tests/no-only-tests: 'error'
plugins:
  - "no-only-tests"
