/* eslint-disable prettier/prettier */

/* FETCHING DATA */
export const FETCH_CVE_LIST_TABLE = 'FETCH_CVE_LIST_TABLE';
export const FETCH_CVE_CLUSTERS_TABLE = 'FETCH_CVE_CLUSTERS_TABLE';
export const FETCH_CVE_IMAGES_TABLE = 'FETCH_CVE_IMAGES_TABLE';
export const FETCH_CLUSTER_LIST_TABLE = 'FETCH_CLUSTER_LIST_TABLE';
export const FETCH_CLUSTER_CVES_TABLE = 'FETCH_CLUSTER_CVES_TABLE';
export const FETCH_CLUSTER_IMAGES_TABLE = 'FETCH_CLUSTER_IMAGES_TABLE';
export const FETCH_CVE_DETAILS = 'FETCH_CVE_DETAILS';
export const FETCH_CLUSTER_DETAILS = 'FETCH_CLUSTER_DETAILS';

/* CHANGING TABLE PARAMS */
export const CHANGE_CVE_LIST_TABLE_PARAMS = 'CHANGE_CVE_LIST_TABLE_PARAMS';
export const CHANGE_CVE_CLUSTERS_TABLE_PARAMS = 'CHANGE_CVE_CLUSTERS_TABLE_PARAMS';
export const CHANGE_CVE_IMAGES_TABLE_PARAMS = 'CHANGE_CVE_IMAGES_TABLE_PARAMS';
export const CHANGE_CLUSTER_LIST_TABLE_PARAMS = 'CHANGE_CLUSTER_LIST_TABLE_PARAMS';
export const CHANGE_CLUSTER_CVES_TABLE_PARAMS = 'CHANGE_CLUSTER_CVES_TABLE_PARAMS';
export const CHANGE_CLUSTER_IMAGES_TABLE_PARAMS = 'CHANGE_CLUSTER_IMAGES_TABLE_PARAMS';

/* CHANGING COLUMNS */
export const CHANGE_CVE_LIST_TABLE_COLUMNS = 'CHANGE_CVE_LIST_TABLE_COLUMNS';
export const CHANGE_CVE_CLUSTERS_TABLE_COLUMNS = 'CHANGE_CVE_CLUSTERS_TABLE_COLUMNS';
export const CHANGE_CVE_IMAGES_TABLE_COLUMNS = 'CHANGE_CVE_IMAGES_TABLE_COLUMNS';
export const CHANGE_CLUSTER_LIST_TABLE_COLUMNS = 'CHANGE_CLUSTER_LIST_TABLE_COLUMNS';
export const CHANGE_CLUSTER_CVES_TABLE_COLUMNS = 'CHANGE_CLUSTER_CVES_TABLE_COLUMNS';
export const CHANGE_CLUSTER_IMAGES_TABLE_COLUMNS = 'CHANGE_CLUSTER_IMAGES_TABLE_COLUMNS';
