/* FETCHING DATA */
export const FETCH_CVE_LIST_TABLE = 'FETCH_CVE_LIST_TABLE';
export const FETCH_CVE_DETAIL_TABLE = 'FETCH_CVE_DETAIL_TABLE';
export const FETCH_CLUSTER_LIST_TABLE = 'FETCH_CLUSTER_LIST_TABLE';
export const FETCH_CLUSTER_DETAIL_TABLE = 'FETCH_CLUSTER_DETAIL_TABLE';
export const FETCH_CVE_DETAILS = 'FETCH_CVE_DETAILS';
export const FETCH_CLUSTER_DETAILS = 'FETCH_CLUSTER_DETAILS';

/* CHANGING TABLE PARAMS */
export const CHANGE_CVE_LIST_TABLE_PARAMS = 'CHANGE_CVE_LIST_TABLE_PARAMS';
